---
- hosts: tag_Name_dummyapp_001,tag_Name_dummyapp_002
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Install app dependencies.
      apt: "name={{ item }} state=present"
      with_items:
        - libsqlite3-dev
        - libreadline-dev
        - ruby-dev
        - libgmp3-dev
        - libpq-dev
        - build-essential
        - git

    - name: Ensure app directory exists and is writeable.
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0755
